CREATE OR REPLACE TABLE DBT_LEARN.ANALYTICS.CUSTOMER_SIMULATION AS
SELECT
    C_CUSTKEY AS customer_id,
    C_NAME AS customer_name,
    C_MKTSEGMENT AS market_segment,
    C_ACCTBAL AS account_balance,
    C_NATIONKEY AS nation_id
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
LIMIT 100;

UPDATE DBT_LEARN.ANALYTICS.CUSTOMER_SIMULATION
SET market_segment = 'MACHINERY'
WHERE customer_id IN (60001, 60002, 60003);

SELECT customer_id, customer_name, market_segment
FROM DBT_LEARN.ANALYTICS.CUSTOMER_SIMULATION
WHERE customer_id IN (60001, 60002, 60003);
