UPDATE DBT_LEARN.ANALYTICS.CUSTOMER_SIMULATION
SET market_segment = 'BUILDING'
WHERE customer_id = 60001;

UPDATE DBT_LEARN.ANALYTICS.CUSTOMER_SIMULATION
SET account_balance = 9999.99
WHERE customer_id = 60002;
