-- 問 1: 外部キー整合性の確認
-- ORDERS に存在するが CUSTOMER に存在しない O_CUSTKEY を探す
SELECT DISTINCT o.O_CUSTKEY
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c
    ON o.O_CUSTKEY = c.C_CUSTKEY
WHERE c.C_CUSTKEY IS NULL;
-- → 0行が返る（整合性が保たれている）


-- 問 2: 全テーブルの行数
SELECT 'ORDERS' AS table_name, COUNT(*) AS row_count FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
UNION ALL SELECT 'CUSTOMER', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
UNION ALL SELECT 'LINEITEM', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
UNION ALL SELECT 'NATION', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION
UNION ALL SELECT 'REGION', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION
UNION ALL SELECT 'PART', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART
UNION ALL SELECT 'SUPPLIER', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER
UNION ALL SELECT 'PARTSUPP', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP
ORDER BY row_count DESC;


-- 問 3: 注文金額 TOP 5（顧客名・国名付き）
SELECT
    o.O_ORDERKEY AS order_id,
    c.C_NAME AS customer_name,
    n.N_NAME AS nation_name,
    o.O_TOTALPRICE AS total_price,
    o.O_ORDERDATE AS order_date
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c
    ON o.O_CUSTKEY = c.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n
    ON c.C_NATIONKEY = n.N_NATIONKEY
ORDER BY o.O_TOTALPRICE DESC
LIMIT 5;
