-- ============================================
-- Lesson 3 Step 8: 全体片付け
-- ============================================

DROP CORTEX SEARCH SERVICE IF EXISTS CORTEX_SEARCH_LEARN.SEARCH.KB_SEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS CORTEX_SEARCH_LEARN.SEARCH.TECH_DOCS_SEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS CORTEX_SEARCH_LEARN.SEARCH.FAQ_SEARCH;
DROP TABLE IF EXISTS CORTEX_SEARCH_LEARN.DATA.KNOWLEDGE_BASE;
DROP TABLE IF EXISTS CORTEX_SEARCH_LEARN.DATA.TECH_DOCS;
DROP TABLE IF EXISTS CORTEX_SEARCH_LEARN.DATA.PRODUCT_FAQ;
-- DROP DATABASE IF EXISTS CORTEX_SEARCH_LEARN;  -- 全削除する場合はコメント解除
