-- TASK を停止・削除
ALTER TASK DBT_LEARN.DBT_PROJECTS.DAILY_DBT_BUILD SUSPEND;
DROP TASK IF EXISTS DBT_LEARN.DBT_PROJECTS.DAILY_DBT_BUILD;

-- dbt プロジェクトを削除
DROP DBT PROJECT IF EXISTS DBT_LEARN.DBT_PROJECTS.LEARN_PROJECT;